MBEx/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from MBEx import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("member/", include("member.urls")),
    path("board/", include("board.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
from django.urls.conf import path
from board import views

app_name = "board"

urlpatterns = [
    path("list", views.ListView.as_view(), name="list" ),
    path("write", views.WriteView.as_view(), name="write" ),
    path("detail", views.DetailView.as_view(), name="detail" ),
    path("delete", views.DeleteView.as_view(), name="delete" ),
    path("modify", views.ModifyView.as_view(), name="modify" ),
    path("modifypro", views.ModifyProView.as_view(), name="modifypro" ),
    path("image", views.ImageView.as_view(), name="image"),
    path("imagedown", views.ImageDown.as_view(), name="imagedown"),
    ]

board/models.py
from django.db import models

# Create your models here.
class Board( models.Model ) :
    num = models.AutoField( verbose_name="글번호", primary_key=True ) # verbose_name 은 어드민에 출력되는 이름
    writer = models.CharField( max_length=30, verbose_name="작성자", null=False )
    subject = models.CharField( max_length=300, verbose_name="글제목", null=False )
    passwd = models.CharField( max_length=20, verbose_name="비밀번호", null=False )
    content = models.CharField( max_length=2000, verbose_name="글내용", null=False )
    readcount = models.IntegerField( verbose_name="조회수", default=0 )
    ref = models.IntegerField( verbose_name="그룹화 아이디" )
    restep = models.IntegerField( verbose_name="글순서" )
    relevel = models.IntegerField( verbose_name="글레벨" )
    regdate = models.DateTimeField( auto_now_add=True, verbose_name="작성일", blank=True )
    ip = models.CharField( max_length=30, verbose_name="아이피" )
    
class ImageBoard(models.Model):
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="images") # 미디어 패키지 밑에 경로를 추가할것이라면 경로를 추가 해 주어야함 /media는 생략
                                                    # 그럼 경로는 media/images 라고 됨

board/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.template import loader
from django.http.response import HttpResponse
from board.models import Board, ImageBoard
import logging
from django.utils.dateformat import DateFormat
from datetime import datetime
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

logger = logging.getLogger(__name__) # 로거표시

PAGE_SIZE = 5 # 한페이지에 5개의 글
PAGE_BLOCK = 3  # 넘어가는것 3개


# 리스트
class ListView( View ) :
    def get(self, request ) :
        template = loader.get_template( "list.html" )
        count = Board.objects.all().count() # 글 전체의 갯수, Board에 있는 count
        
        pagenum = request.GET.get( "pagenum" ) # 페이지num
        if not pagenum :
            pagenum = "1"
        
        pagenum = int( pagenum ) # 페이지num 을 보겠다
        
        # 한 페이지에 몇개씩 표기하겠다를 정해주어야함
        start = ( pagenum - 1) * int(PAGE_SIZE)        # ( 5 - 1 ) * 10  + 1    41
        end = start + int(PAGE_SIZE)                # 41 + 10 - 1            50
        if end > count :
            end = count
        
        # 리스트임
        dtos = Board.objects.order_by( "-ref", "restep" )[start:end] # 같은 그룹이면서, 나중에 쓴 글을올려야함, ref를 내림차순, restep을 오름차순으로 정렬
                                                                    # 슬라이싱은 0부터 시작함
                                                                    # 슬라이싱이 -1이라 글을 하나 적게 가져옴
                                                                    # start 부터 end 까지 잘라서 가져와라
                                                                  
        # 글번호 출력도 계산해야함                                                
        number = count - ( pagenum - 1 ) * int(PAGE_SIZE)
        
        # 페이지 넘기기
        startpage = pagenum // int(PAGE_BLOCK) * int(PAGE_BLOCK) + 1      # 9 // 10 * 10 + 1    1
        if pagenum % int(PAGE_BLOCK) == 0 :
            startpage -= int(PAGE_BLOCK) # 페이지 고정
        endpage = startpage + int(PAGE_BLOCK) - 1                         # 1 + 10 -1           10
        pagecount = count // int(PAGE_SIZE)
        if count % int(PAGE_SIZE) > 0 :
            pagecount += 1
        if endpage > pagecount :
            endpage = pagecount  
        pages = range( startpage, endpage+1 )    
        context = {
            "count" : count,
            "dtos" : dtos,
            "pagenum" : pagenum,
            "number" : number,
            "pages" : pages,
            "startpage" : startpage,
            "endpage" : endpage,
            "pageblock" : PAGE_BLOCK,
            "pagecount" : pagecount,
            }
        return HttpResponse( template.render( context, request ) )
    def post(self, request ) :
        pass
    

# 글 작성
class WriteView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(WriteView, self ).dispatch( request, *args, **kwargs )
    
    def get(self,request):
        ref=1
        restep=0
        relevel=0
        # num=request.GET["num"] 에러발생
        # 받는것이 두가지방법이있음
        num = request.GET.get("num") # 예외 하나가 자동으로 잡힘, 보통은 이렇게 잡음 에러방지를 위해 받기도함
        if num == None :
            # 제목글 이라는뜻
            try : # 글이 있는경우
                maxnum = Board.objects.order_by("-num").values()[0]["num"] # num으로 내림차순 정렬, 맨 위의 것
                ref = maxnum + 1        # 그룹화 아이디 글번호 최대값 + 1
                
            except IndexError:
                # 글이 없는 경우
                ref = 1
                
        else :
            # 답변글 이라는뜻
            # 나중에 쓴 답글은 위로 올라가야함
            # ref = request.GET["ref"]
            # restep = request.GET["restep"]
            # relevel = request.GET["relevel"]
            ref = request.GET["ref"]
            restep = request.GET["restep"]
            relevel = request.GET["relevel"]
            res = Board.objects.filter(ref__exact=ref).filter(restep__gt=restep) # gt, 크냐로 들어감 get, 순서 중요, 체이닝 이용해서 할것
            for re in res :
                re.restep = int(re.restep) + 1 # 원레는 +1 해주면 되는데 자료형이 안넘어와 강제 형변환필요
                re.save()
            
            restep = int(restep) + 1
            relevel = int(relevel) + 1
        
        # write 폼으로 넘어갔다가 다시 post로 넘어감
        template = loader.get_template( "writearticle.html" )
        context = {
            "num" : num,
            "ref" : ref,
            "restep" : restep,
            "relevel" : relevel,
            }
        return HttpResponse( template.render( context, request ) )
    
    def post(self,request):
        dto = Board(
            writer = request.POST["writer"],
            subject = request.POST["subject"],
            passwd = request.POST["passwd"],
            content = request.POST["content"],
            readcount = 0, # 이건 없어도됨
            ref = request.POST["ref"],
            restep = request.POST["restep"],
            relevel = request.POST["relevel"],
            regdate = DateFormat(datetime.now()).format("Ymd"),
            ip = request.META.get("REMOTE_ADDR")
            )
        dto.save()
        return redirect("board:list")
    
# 글 보기
class DetailView(View):
    def get(self,request):
        num = request.GET["num"]
        pagenum = request.GET["pagenum"]
        number = request.GET["number"]
        dto = Board.objects.get(num=num)
        if dto.ip != request.META.get("REMOTE_ADDR") : # 현재 접속중인 아이피와 디비의 아이피 비교
            dto.readcount += 1
            dto.save()
        context = {
            "num" : num,
            "pagenum" : pagenum,
            "number" : number,
            "dto" : dto,
            }
        template = loader.get_template("detailarticle.html")
        return HttpResponse(template.render(context,request))
    
    def post(self,request):
        pass
    
# 글 삭제
class DeleteView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(DeleteView,self).dispatch(request, *args, **kwargs)
    
    def get(self,request): # 비밀번호 확인 페이지
        num = request.GET["num"]
        pagenum = request.GET["pagenum"]
        template = loader.get_template("deletearticle.html")
        context = {
            "num" : num,
            "pagenum" : pagenum,
            }
        return HttpResponse(template.render(context,request))
        
    def post(self,request):
        num = request.POST["num"]
        pagenum = request.POST["pagenum"]
        passwd = request.POST["passwd"]
        dto = Board.objects.get( num = num )
        
        # 비밀번호 확인을 해주어야함
        if passwd == dto.passwd :
            # 비밀번호가 같다                                            # restep이 1개 큰 애
            res = Board.objects.filter( ref__exact=dto.ref ).filter( restep__exact=dto.restep+1 ).filter( relevel__gt=dto.relevel ) # 데이터가 있으면 댓글이 있다
            logger.info(res) # 로그 보기, 로그에서 queryset은 객체이다. 
            if len(res)==0 :
                # 댓글이 없는 경우                
                dto.delete()                                                
            else :
                # 댓글이 있는 경우
                dto.readcount = -1
                dto.save()
            return redirect( "board:list" ) # 삭제후 해당 페이지번호로 이동해야 하지만, 삭제가 안됨
        else :
            # 비밀번호가 다르다
            template = loader.get_template( "deletearticle.html" )
            context = {
                "num" : num,
                "pagenum" : pagenum,
                "message" : "비밀번호가 다릅니다",
                }
            return HttpResponse( template.render( context, request ) )


# 글 수정 비밀번호 확인
class ModifyView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(ModifyView,self).dispatch(request, *args, **kwargs)
    
    def get(self,request):
        num = request.GET["num"]
        pagenum = request.GET["pagenum"]
        context = {
            "num" : num,
            "pagenum" : pagenum,
            }
        template = loader.get_template("modifyarticle.html")
        return HttpResponse(template.render(context,request))
        
    def post(self,request):
        # 비밀번호 확인후 수정페이지로 넘기기
        num = request.POST["num"]
        pagenum = request.POST["pagenum"]
        passwd = request.POST["passwd"]
        dto = Board.objects.get(num=num)
        
        # 비밀번호가 같다
        if passwd == dto.passwd :
            template = loader.get_template("modifyproarticle.html")
            context = {
                "num" : num,
                "pagenum" : pagenum,
                "dto" : dto,
                }
            return HttpResponse(template.render(context,request))
        
        # 비밀번호가 다르다
        else :
            template = loader.get_template("modifyarticle.html")
            context = {
                "num":num,
                "pagenum":pagenum,
                "message" : "비밀번호 다릅니다",
                }
            return HttpResponse(template.render(context,request))


# 수정처리
class ModifyProView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(ModifyProView,self).dispatch(request, *args, **kwargs)
    
    def get(self,request):
        pass
    
    def post(self,request):
        num = request.POST["num"]
        pagenum = request.POST["pagenum"]
        dto = Board.objects.get(num=num)

        # newdto로 새로 덮어도 되지만
        dto.subject = request.POST["subject"]
        dto.content = request.POST["content"]
        dto.passwd = request.POST["passwd"]
        dto.save()
        return redirect("board:list")


class ImageView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(ImageView,self).dispatch(request, *args, **kwargs)
    
    def get(self,request):
        template = loader.get_template("imageupload.html")
        context = {}
        return HttpResponse(template.render(context,request))
    def post(self,request):
        title = request.POST["title"]

board/templates/base_board.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
		<link type="text/css" rel="stylesheet" href="{% static 'css/style_board.css'%}">
		<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
	</head>
	<body>
		{% block title %} <h2> 게시판 </h2> {% endblock %}
		{% block header %} 상단메뉴 {% endblock %}
		<br>
		<br>
		{% block contents %}
		
		
		
		
		
		{% endblock %}
		<br>
		{% block footer %} 하단메뉴 {% endblock %}
	</body>
</html>

board/templates/deletearticle.html
{% extends "base_board.html" %}
{% block title %} <h2> 글 삭제 </h2> {% endblock %}

{% block contents %}
{% csrf_token %}
<form method="post" name="deleteform" action="delete">
	<input type="hidden" name="num" value="{{num}}">
	<input type="hidden" name="pagenum" value="{{pagenum}}">
	<table>
		<tr>
			<th colspan="2">
				{% if message %}
					{{message}}
					
				{% else %}
					비밀번호를 입력해
				{% endif %}
			</th>
		</tr>
		<tr>
			<th> 비밀번호</th>
			<td><input class="input" type="password" name="passwd">
		</tr>
		<tr>
			<th colspan="2">
				<input class="inputbutton" type="submit" value="삭제">
				<input class="inputbutton" type="button" value="삭제취소"
					onclick="location='list?pagenum={{pagenum}}'">
			</th>
		</tr>
	</table>
</form>
{% endblock %}

board/templates/detailarticle.html
{% extends "base_board.html" %}
{% block title %} <h2> 글 보 기</h2> {% endblock %}

{% block contents %}
<table>
	<tr>
		<th> 글 번호 </th>
		<td style="text-align:center"> {{number}} </td>
		<th> 조회수 </th>
		<td style = "text-align:center"> {{dto.readcount}} </td>
	</tr>
	<tr>
		<th> 작성자 </th>
		<td style = "text-align:center"> {{dto.writer}} </td>
		<th> 작성일 </th>
		<td style = "text-align:center"> {{dto.regdate|date:"Y-m-d H:i"}} </td>
	</tr>
	<tr>
		<th> 제목 </th>
		<td colspan="3"> {{dto.subject}} </td>
	</tr>
	<tr>
		<th> 내용 </th>
		<td colspan="3"> <pre>{{dto.content}}</pre> </td>
	</tr>
	<tr>
		<th colspan="4">
			<input class="inputbutton" type="button" value="수정"
				onclick="location='modify?num={{dto.num}}&pagenum={{pagenum}}'">
			<input class="inputbutton" type="button" value="삭제"
				onclick="location='delete?num={{dto.num}}&pagenum={{pagenum}}'">
			<input class="inputbutton" type="button" value="답글"
				onclick="location='write?num={{dto.num}}&ref={{dto.ref}}&restep={{dto.restep}}&relevel={{dto.relevel}}'">
			<input class="inputbutton" type="button" value="목록"
				onclick="location='list?pagenum={{pagenum}}'">
		</th>
	</tr>
</table>
{% endblock %}

board/templates/imagedown.html
{% extends "base_board.html" %}

{% block title %} <h2> 이미지 다운로드 </h2> {% endblock %}

{% block contents %}

{% for dto in dtos %}
	<!-- 이미지 이름, 사진 반복문 출력 --> <!-- 절대경로 -->
	{{dto.title}}<br>
	{{dto.photo}}<br>
	{{dto.photo.path}}<br>

	<img src="{{dto.photo.url}}" border="0" width="200" height="100">

{% endfor %}
{% endblock %}

board/templates/imageupload.html
{% extends "base_board.html" %}

{% block title %} <h2> 이미지 업로드 </h2> {% endblock %}

{% block contents %}
{% csrf_token %}
<!-- enctype은 꼭 주어야한다 안그러면 에러남 -->
<form method="post" action="image" enctype="multipart/form-data">
	<table>
		<tr>
			<th> 제목 </th>
			<td><input class="input" type="text" name="title"></td>
		</tr>
		<tr>
			<th> 이미지 </th>
			<td><input type="file" name="photo"></td>
		</tr>
		<tr>
			<th colspan="2">
				<input class="inputbutton" type="submit" value="업로드">
				<input class="inputbutton" type="reset" value="취소">
			</th>
		</tr>
	</table>
</form>
{% endblock %}

board/templates/list.html
{% extends "base_board.html" %}

{% block title %} <h2> 글 목 록 ( 전체글 : {{count}} )</h2> {% endblock %}

{% block contents %}

{% load mathfilters %}
{% load static %}
<table>
	<tr>
		<td style="text-align:right" colspan="6">
			<!-- app_name을 쓴경우 urls의 name의 이름을 써주어야함 -->
			<a href="{% url 'board:write' %}">글쓰기</a>&nbsp;&nbsp;&nbsp; 
		</td>
	</tr>
	<tr>
		<th style="width:8%"> 글번호 </th>
		<th style="width:40%"> 제목 </th>
		<th style="width:15%"> 작성자 </th>
		<th style="width:8%"> 조회수 </th>
		<th style="width:15%"> 작성일 </th>
		<th style="width:15%"> IP </th>
	</tr>
	{% if count == 0 %}	
		<tr>
			<td colspan="6" style="text-align:center">
				게시판에 글이 없습니다. 글쓰기 눌러주세요
			</td>
		</tr>		
	{% else %}
		{% for dto in dtos %}
			<tr>
				<td style="text-align:center">
					<!-- number-1 이게 불가능함, 이안에서 작업을 할 수가 없음, 단순 변수 출력하는 구문임 -->
					<!-- number 는 무조건 10임 -->
					<!-- 반복문 돌때마다 증가하는값을 넣어주어야함 -->
					{{number|sub:forloop.counter0}}
				</td>
				<td>
					{% if dto.readcount == -1 %}
						삭제된 글입니다
					{% else %}
						{% if dto.relevel > 1 %}
							<img src="{% static 'images/level.gif'%}" border=0 height=20
								width="{{dto.relevel|mul:7}}">
						{% endif %}
						{% if dto.relevel > 0 %}
							<img src="{% static 'images/re.gif'%}" border=0 width="15">						
						{% endif %}					
						<a href="detail?num={{dto.num}}&pagenum={{pagenum}}&number={{number|sub:forloop.counter0}}">
							{{dto.subject}}
						</a>
					{% endif %}	
				</td>
				<td style="text-align:center">
					{{dto.writer}}
				</td>
				<td style="text-align:center">
					<!-- -1 일경우 아무것도 출력하지 않는다. -->
					{% if dto.readcount == -1 %}
						&nbsp;
					{% else %}
						{{dto.readcount}}
					{% endif %}
				</td>
				<td style="text-align:center">
					{{dto.regdate|date:"Y-m-d H:i"}}
				</td>
				<td style="text-align:center">
					{{dto.ip}}
				</td>
			</tr>
		{% endfor %}
	{% endif %}
</table>
<br>

{% if startpage > pageblock %}
	<a href="list?pagenum={{startpage|sub:pageblock}}">[◀]</a>
{% endif %}
<!-- range가 안들어감, range(stratrpage, endpage), 이런식인데 사용하지 못하기에 pages라고 만들어서 가져옴 -->
{% for page in pages %}
	<!-- 현재 보는 페이지랑 같다 -->
	{% if pagenum == page %}
		<b>[{{page}}]</b>
	<!-- 다르다 -->
	{% else %}
		<a href="list?pagenum={{page}}">[{{page}}]</a>
	{% endif %}	
{% endfor %}
{% if endpage < pagecount %}
	<a href="list?pagenum={{startpage|add:pageblock}}">[▶]</a>
{% endif %}
	
{% endblock %}

board/templates/modifyarticle.html
{% extends "base_board.html" %}
{% block title %} <h2> 글 수정 </h2> {% endblock %}

{% block contents %}
{% csrf_token %}
<form method="post" name="modifyform" action="modify">
	<input type="hidden" name="num" value="{{num}}">
	<input type="hidden" name="pagenum" value="{{pagenum}}">
	<table>
		<tr>
			<th colspan="2">
				{% if message %}
					{{message}}
					
				{% else %}
					비밀번호를 입력해
				{% endif %}
			</th>
		</tr>
		<tr>
			<th> 비밀번호</th>
			<td><input class="input" type="password" name="passwd">
		</tr>
		<tr>
			<th colspan="2">
				<input class="inputbutton" type="submit" value="수정">
				<input class="inputbutton" type="button" value="수정취소"
					onclick="location='list?pagenum={{pagenum}}'">
			</th>
		</tr>
	</table>
</form>
{% endblock %}

board/templates/modifyproarticle.html
{% extends "base_board.html" %}
{% block title %}<h2> 글 수정 </h2>{% endblock %}

{% block contents %}
{% csrf_token %}
<form name="modifyproform" method="post" action="modifypro">
	<input type="hidden" name="num" value="{{num}}">
	<input type="hidden" name="pagenum" value="{{pagenum}}">
	<table>
		<tr>
			<th colspan="2">
				수정할 정보를 입력하세요
			</th>
		</tr>
		<tr>
			<th>작성자</th>
			<td>&nbsp; {{dto.writer}}
		</tr>
		<tr>
			<th>글 제목</th>
			<td><input class="input" type="text" name="subject" value="{{dto.subject}}">
		</tr>
		<tr>
			<th>글 내용</th>
			<td><textarea name="content" rows="10" cols="35">{{dto.content}}</textarea>
		</tr>
		<tr>
			<th>비밀번호</th>
			<td><input class="input" type="password" name="passwd" value="{{dto.passwd}}">
		</tr>
		<tr>
			<th colspan="2">
				<input class="inputbutton" type="submit" value="수정">
				<input class="inputbutton" type="reset" value="취소">
				<input class="inputbutton" type="button" value="수정취소"
					onclick="location='list?pagenum={{pagenum}}'">
			</th>
		</tr>
	</table>
</form>
{% endblock %}

board/templates/writearticle.html
{% extends "base_board.html" %}

{% block title %} <h2> 글쓰기 </h2> {% endblock %}


{% block contents %}
{% csrf_token %}
	<form method="post" name="writeform" action="write"> <!-- writeView 로 넘어가는것 링크가 write임 -->
		<input type="hidden" name="ref" value="{{num}}">
		<input type="hidden" name="ref" value="{{ref}}">
		<input type="hidden" name="restep" value="{{restep}}">
		<input type="hidden" name="relevel" value="{{relevel}}">
		<table>
			<tr>
				<th colspan="2">
					글작성 정보를 입력하세요
				</th>
			</tr>
			<tr>
				<th> 작성자 </th>
				<td><input class="input" type="text" name="writer"></td>
			</tr>
			<tr>
				<th> 제목 </th>
				<td><input class="input" type="text" name="subject"></td>
			</tr>
			<tr>
				<th> 내용 </th>
				<td><textarea name="content" rows="10" cols="35"></textarea></td>
			</tr>
			<tr>
				<th> 비밀번호 </th>
				<td><input class="input" type="password" name="passwd"></td>
			</tr>
			<tr>
				<th colspan="2">
					<input type="submit" class="inputbutton" value="작성">
					<input type="reset" class="inputbutton" value="취소">
					<input type="button" class="inputbutton" value="목록"
						onclick="location='list'">
				</th>
			</tr>
		</table>
	</form>
{% endblock %}